// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIgbUO3AoINJVuzpupdtWCAI4f-g3iMRc',
    appId: '1:2426197313:web:dea86fc7c42d5392273dc0',
    messagingSenderId: '2426197313',
    projectId: 'testflutterfcm-bac2a',
    authDomain: 'testflutterfcm-bac2a.firebaseapp.com',
    storageBucket: 'testflutterfcm-bac2a.appspot.com',
    measurementId: 'G-4E5SR55Y66',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNkoc-QnrFHvbFIWfvE0-Qm4pYeBo-VYI',
    appId: '1:2426197313:android:9309cae5efaaafd3273dc0',
    messagingSenderId: '2426197313',
    projectId: 'testflutterfcm-bac2a',
    storageBucket: 'testflutterfcm-bac2a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLriQXeeIdqFk7qmDj6GjEpw7YWrFufV4',
    appId: '1:2426197313:ios:3c794cf913f58dc4273dc0',
    messagingSenderId: '2426197313',
    projectId: 'testflutterfcm-bac2a',
    storageBucket: 'testflutterfcm-bac2a.appspot.com',
    iosClientId:
        '2426197313-kt4nht5u784mnm17vmicrh7he7j5jpj6.apps.googleusercontent.com',
    iosBundleId: 'com.example.testFlutterFcm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLriQXeeIdqFk7qmDj6GjEpw7YWrFufV4',
    appId: '1:2426197313:ios:3c794cf913f58dc4273dc0',
    messagingSenderId: '2426197313',
    projectId: 'testflutterfcm-bac2a',
    storageBucket: 'testflutterfcm-bac2a.appspot.com',
    iosClientId:
        '2426197313-kt4nht5u784mnm17vmicrh7he7j5jpj6.apps.googleusercontent.com',
    iosBundleId: 'com.example.testFlutterFcm',
  );
}
